language: node_js
node_js:
  - "0.10"
script: "npm test"
after_success:
  - ./node_modules/istanbul/lib/cli.js cover node_modules/mocha/bin/mocha --report lcovonly -- -R spec lib/**/*.test.js
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - rm -rf ./coverage
