language: node_js
node_js:
  - "0.10"
script: "npm test"
after_success:
  - ./node_modules/.bin/jscoverage lib
  - ./node_modules/.bin/mocha lib/**/*.js -R mocha-lcov-reporter | ./node_modules/coveralls/bin/coveralls.js