language: node_js
node_js:
  - "0.10"
script: "npm test"
after_success:
  - ./node_modules/.bin/jscoverage lib lib-cov
  - ./node_modules/.bin/mocha **/*.js -R mocha-lcov-reporter | ./node_modules/coveralls/bin/coveralls.js