#!/usr/bin/env node

require('./is-modular')(process.argv.slice(2), _display)

function _display(err, results) {
  var errored = false
  var erroredFilesCount = 0
  var errorsCount = 0

  if (err) {
    console.error('Unexpected error:'.bold.red, err)
    process.exit(1)
    return
  }

  if (!results.length) {
    console.error('No files found.'.bold.red)
    process.exit(1)
    return
  }


  results.forEach(function (result) {
    if (!result.modular) {
      erroredFilesCount++
      console.error('"%s":'.red, result.filename)
      result.errors.forEach(function (error) {
        errorsCount++
        console.error(
          '\tat %s:0, "%s": %s'.red,
          error.details.line,
          error.details.badRequire,
          error.description
        )
      })
      errored = true
    }
  })

  if (errored) {
    console.error('\nOh boy..\n%s error(s) found in %s file(s)!'.red.bold, erroredFilesCount, errorsCount)
    process.exit(1)
  }
  console.log('%s files checked.', results.length)
  console.log('Yeay! Everything is modular! o/'.rainbow)
  process.exit(0)
}